language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=luajit2.1

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install moonscript
  - luarocks make

script:
  make test
